### ISSUE TITLE
Erreur

### ISSUE THREAD

**Issue by cb03** [mqu/php-console-freebox#3]
Bonour, j'obtiens cette erreur chez OVH :

Parse error: syntax error, unexpected T_STRING, expecting T_OLD_FUNCTION or T_FUNCTION or T_VAR or '}' in /homez.379/creationvf/www/Page.php on line 6

sinon avec un serveur perso j'arrive sur la page d’accueil, je me connecte et j'obtiens le message :

Warning: curl_setopt() [function.curl-setopt]: CURLOPT_FOLLOWLOCATION cannot be activated when in safe_mode or an open_basedir is set in /home/fabrice/domains/n********cet.info/public_html/FREE/CURL.php on line 11
connexion réussie 

lorsque je clique sur lister  j'obtiens :
## id = 10019648 ; idt=142e31a1caa9dc36

Warning: curl_setopt() [function.curl-setopt]: CURLOPT_FOLLOWLOCATION cannot be activated when in safe_mode or an open_basedir is set in /home/fabrice/domains/cr******cet.info/public_html/FREE/CURL.php on line 11

Warning: is_file() [function.is-file]: open_basedir restriction in effect. File(HTTP/1.1 200 OK Date: Wed, 13 Apr 2011 18:56:02 GMT Server: Apache Connection: close Transfer-Encoding: chunked Content-Type: text/html; charset=ISO-8859-1 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head>  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /> <meta http-equiv="Content-Language" content="fr" /> <meta name="robots" content="noindex,nofollow" /> <meta name="keywords" content="Free, adsl, offres adsl, internet, t&eacute;l&eacute;phone, t&eacute;l&eacute;phonie, mobiles, forfaits mobiles, tv, t&eacute;l&eacute;vision, VOD, vid&eacute;o � la demande, multiposte, radio, wifi, in /home/fabrice/domains/c******cet.info/public_html/FREE/simplehtmldom.php on line 514
X - [135] - TF1 - 16/04/2011 17:45 (80mn) - TOUS ENSEMBLE
X - [136] - M6 - 17/04/2011 18:37 (75mn) - DECO
X - [138] - TF1 - 15/04/2011 20:39 (180mn) - EXPLORATEUR
X - [133] - France 2 - 14/04/2011 17:50 (75mn) - ON NE
X - [134] - France 2 - 15/04/2011 17:50 (75mn) - ON NE

Quand je clique sur programmer, les champs a compléter  s'affichent et en dessous j'ai ceci qui s'affiche :

Array
(
    [action] => programmer
    [PHPSESSID] => cd3137699aa59ad1ec02afd790d6db5d
)
Array
(
    [date] => 13/04/2011
    [heure] => 08
    [minutes] => 55
    [duree] => 10
    [chaine] => 2
    [qualite] => auto
    [emission] => test
    [id] => 10019648
    [idt] => 142e31a1caa9dc36
)

**Comment by mqu** [comment]
hello ; je n'avais pas vu ton message ;

je regarde des que j'ai un peu de temps. J'ai apporté de nombreuses modifications sur le dépot ; globalement cela devrait fonctionner, j'essaie de pusher uniquement des sources globalement fonctionnel, mais dans mon esprit c'est encore un peu en vrac. En particulier, l'interface Web ne permet plus de réaliser les enregistrements.

Il me faudrait figer une version ; mais en fait l'interface Web est pas loin d'être fini, mais j'avais à la vitesse de l'escargot. Actuellement, seules la ligne de commande est fonctionnelle.

Personnellement, j'ai un petit hébergement VPS chez OVH.
cordialement.

**Comment by cb03** [comment]
Bonjour, déjà merci pour ce script ! je viens d'essayer le nouvelle version. Je me connecte puis clique sur lister ou programmer, et je tombe sur cette erreur :

une erreur s'est produite : Cache: this directory is not writable (var/cache)

**Comment by mqu** [comment]
oui : dans le répertoire ou il y a les sources, tu peux lancer les commandes : 
 mkdir -p var/cache
 chmod ugo+rwx var var/cache

bonnes nouvelles : ca fonctionne chez moi ; je n'ai pas encore testé la version clonée depuis GIT ; mais d'ici 1 ou 2 jours ca devrait le faire !

**Comment by mqu** [comment]
je vais fermer cet incident ; s'il y a du nouveau, il faudra que tu en ouvre un nouveau.
