### ISSUE TITLE
Recurrence

### ISSUE THREAD

**Issue by cb03** [mqu/php-console-freebox#4]
Bonsoir,

Je viens de tester la nouvelle interface. Tout marche bien mais la programmation ne tient pas en compte des jours sélectionnés.

Par exemple, j'ai choisi d'enregistrer que le dimanche, avec 10 occurrences. Le script m'a programmé 10 enregistrements mais tous les jours, sur une longueur de 10 jours. Et non uniquement les dimanches comme je l'aurais souhaité.

On dirait que le check, ce dé-sélectionne tout de suite après l’envoi du premier enregistrement.

Pour info j'utilise firefox.

**Comment by mqu** [comment]
exact !

en principe ca devrait fonctionner, d'autant que j'ai développé la classe permettant de le faire (classe EnregistrementRecurrent). Le bug sera très vite corrigé.

cordialement.

**Comment by cb03** [comment]
Super !

**Comment by mqu** [comment]
c'est bon, ca doit marcher maintenant !
