### ISSUE TITLE
Page lister erreurs

### ISSUE THREAD

**Issue by cb03** [mqu/php-console-freebox#5]
Bonsoir,

J'ai toujours les erreurs dans la page lister, mais elles ne m’empêchent pas d'utiliser le script :

Warning: curl_setopt() [function.curl-setopt]: CURLOPT_FOLLOWLOCATION cannot be activated when in safe_mode or an open_basedir is set in /home/fabrice/domains/creations.info/public_html/FREE/CURL.php on line 13

Warning: is_file() [function.is-file]: open_basedir restriction in effect. File(HTTP/1.1 200 OK Date: Fri, 15 Apr 2011 22:27:40 GMT Server: Apache Connection: close Transfer-Encoding: chunked Content-Type: text/html; charset=ISO-8859-1 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head>  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /> <meta http-equiv="Content-Language" content="fr" /> <meta name="robots" content="noindex,nofollow" /> <meta name="keywords" content="Free, adsl, offres adsl, internet, t&eacute;l&eacute;phone, t&eacute;l&eacute;phonie, mobiles, forfaits mobiles, tv, t&eacute;l&eacute;vision, VOD, vid&eacute;o à la demande, multiposte, radio, wifi, in /home/fabrice/domains/creations.info/public_html/FREE/simplehtmldom.php on line 514

**Comment by mqu** [comment]
ces erreurs sont je présume sur ton propre hébergement. Je te propose d'aller faire un tour sur mon site en attendant : http://vps11580.ovh.net/fbr/ ; j'ai aussi qq erreurs dans mon fichier de log, mais elles sont moins significatives.

mon hébergement est un tout petit VPS OVH. Je vais essayer de travailler sur les erreurs liées a ton environnement ; je présume qu'elles sont du au fait que c'est un hébergement mutualisé avec des options de type safe-mode.

**Comment by cb03** [comment]
J'ai un kimsufi sur ovh mais je suis loin d'être un pro dans ce domaine. Le safe mode est off et open_basedir on

merci

**Comment by mqu** [comment]
merci pour l'info. C'est donc `open_basedir` qui concentrera toute mon attention dès que j'aurai le temps. Tu sais que tu peux programmer tes enregistrements personnels via la commande en ligne, c'est peut-être ce que tu fais déjà.  J'ai un script permettant de vérifier afficher les dépendances techniques : `check-php-installation.php`.

**Comment by mqu** [comment]
en principe c'est corrigé ; j'ai ajouté le test open_basedir pour éviter le warning. Tu peux mettre a jour tes sources (git pull).

**Comment by mqu** [comment]
j'ai ajouté le "@" pour masquer l'erreur dans simpledomhtml ligne 514 : 
            if (preg_match("/^http:\/\//i",$str) || @is_file($str))

**Comment by cb03** [comment]
Bonjour,

Oui tout marche nickel désormais ! :)

**Comment by mqu** [comment]
merci, je clos.
