### ISSUE TITLE
erreur programmation portant sur le disque dur

### ISSUE THREAD

**Issue by mqu** [mqu/php-console-freebox#7]
lorsqu'on souhaite programmer un enregistrement, cette erreur s'affiche :

`une erreur s'est produite : erreur de programmation : Cette combinaison de cha?ne / service n'est enregistrable que sur le disque interne`

**Comment by mqu** [comment]
analyse du problème : 
- l'interface ne permet pas de choisir actuellement la destination de l'enregistrement,
- les espaces disques sont identifiés par des ID (identifiant numérique), actuellement, le disque interne porte l'identifiant 2,

action : 
- vérifier si l'interface (API) Free n'a pas changé,
- éventuellement, permettre le choix du disque dur, à défaut recharger dynamiquement l'ID du disque, information disponible sur le formulaire en ligne.

**Comment by mqu** [comment]
le problème a disparu. Peut-être lié au cache concernant la liste des chaines ; je ferai en sorte que ce cache expire plus rapidement ou sur réception d'erreurs.

**Comment by trefs** [comment]
ce matin sa marchais mais la le problème est revenu

**Comment by mqu** [comment]
j'ai essayé de faire qq chose rapidement, concernant le cache. Je suppose que le problème est bien lié au cache, je n'en n'ai pas la certitude. Ce WE, je vais essayer de faire qq chose de plus robuste, c'est promis.

Est-ce que tu utilises bien mon serveur avec cette adresse : http://vps11580.ovh.net/fbr/ ?

**Comment by trefs** [comment]
j'utilise bien cette adresse
je sais pas si t' étais déjà intervenu mais 1/2 heure après mon message c’était rentré dans l'ordre

**Comment by cb03** [comment]
Pour moi tout fonctionne bien actuellement ! encore Merci !

**Comment by mqu** [comment]
pas de retour depuis plusieurs jours ; je clos l'incident.
